config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users do
    get :choice, on: :collection
    post :follow, on: :member
    get :logout, on: :member
    get :edit, on: :member
    get :identification, on: :member
    resources :cards, :only => [:index, :new, :create, :destroy]
    resources :orders, only: :index do
      get :sale, on: :collection
      post :pay, on: :member
    end
  end
  resources :items do
    # get :search, on: :collection
    collection do
      match 'search' => 'items#search', via: [:get, :post], as: :search
    end
    get :option, on: :member
    resources :orders, only: [:new, :create, :show, :update, :destroy]
    resources :comments, only: [:create]
  end

  resources :categories do
    get :select_top, on: :collection
    get :select_mid, on: :collection
  end

  resources :brands do
    get :search, on: :collection
    get :submit, on: :collection
  end

  resources :sizes, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sns_credentials
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  validates :nickname, presence: true, length: { maximum: 12 }

  has_many :items
  has_many :credit_cards


  def self.find_for_oauth(auth)
    snscredential = SnsCredential.where(uid: auth.uid, provider: auth.provider).first
    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
          )
      else
        user = User.create(
          nickname: auth.info.name,
          email:    auth.info.email,
          password: Devise.friendly_token[0, 20]
          )
        user_id = user.id
        SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user_id
          )
      end
      user
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def google_oauth2
    callback_from :google
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :redirect_to_choice, :except => [:choice]

  def choice
    render layout: 'layout_content'
  end

  def logout
  end

  def show
    user = User.find(show_params[:id])
    @nickname = user.nickname
    @orders = user.orders.order("created_at DESC").page(params[:page]).per(8)
    @count = user.orders.length
  end

  def edit
    user = User.find(show_params[:id])
  end

  def identification
    @user = User.find(params[:id])
    @address = Address.find_or_initialize_by(id: params[:id])
    @year = (1900..2018).to_a.freeze
    @month = (1..12).to_a.freeze
    @day = (1..31).to_a.freeze
  end

  def update
    user = User.find(params[:id])
    address = Address.find_or_initialize_by(id: params[:id])
    User.transaction do
      user.update!(user_params)
      address.update_attributes!( address_params )
    end
    render :show
    rescue => e
    render :logout
  end

  private
  def redirect_to_choice
    user = User.find(show_params[:id])
    redirect_to :action => "choice" unless user.id == current_user.id
  end

  def show_params
    params.permit(:id)
  end

  def user_params
    params.require(:user).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :birth_year, :birth_month, :birth_day)
  end

  def address_params
    params.require(:user).require(:address).permit(:postal_code, :prefecture, :city, :street_number, :building_name).merge(user_id: current_user.id)
  end

end

app/views/users/_sidebar.haml
.l-side
  %nav.mypage-nav
    %ul.mypage-nav-list
      %li
        = link_to user_path(current_user.id),class: "mypage-nav-list-item" do
          マイページ
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          お知らせ
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          やることリスト
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          いいね！一覧
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          出品する
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          出品した商品・出品中
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          出品した商品・取引中
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          出品した商品・売却済み
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          購入した商品・取引中
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          購入した商品・過去の取引
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          ニュース一覧
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          評価一覧
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          ガイド
          %i.far.fa-angle-rig.fa-lg
      %li
        = link_to "", class: "mypage-nav-list-item" do
          お問い合わせ
          %i.far.fa-angle-rig.fa-lg
  %h3.mypage-nav-head
    売上・ポイント
  %ul.mypage-nav-list
    %li
      = link_to "", class: "mypage-nav-list-item" do
        売上・振込申請
        %i.far.fa-angle-rig.fa-lg
    %li
      = link_to "", class: "mypage-nav-list-item" do
        ポイント
        %i.far.fa-angle-rig.fa-lg
  %h3.mypage-nav-head
    設定
  %ul.mypage-nav-list
    %li
      = link_to edit_user_path, class: "mypage-nav-list-item" do
        プロフィール
        %i.far.fa-angle-rig.fa-lg
    %li
      = link_to "", class: "mypage-nav-list-item" do
        住所変更
        %i.far.fa-angle-rig.fa-lg
    %li
      = link_to "", class: "mypage-nav-list-item" do
        支払い方法
        %i.far.fa-angle-rig.fa-lg
    %li
      = link_to "", class: "mypage-nav-list-item" do
        メール/パスワード
        %i.far.fa-angle-rig.fa-lg
    %li
      = link_to identification_user_path(current_user.id), class: "mypage-nav-list-item" do
        本人情報
        %i.far.fa-angle-rig.fa-lg
      = link_to "", class: "mypage-nav-list-item" do
        電話番号の確認
        %i.far.fa-angle-rig.fa-lg
    %li
      = link_to logout_user_path(current_user.id), class: "mypage-nav-list-item" do
        ログアウト
        %i.far.fa-angle-rig.fa-lg

app/views/users/choice.html.haml
%main.single-main
  %section.l-single-container
    %h2.l-single-head 新規会員登録
    .l-single-inner
      .l-single-content
        = link_to new_user_registration_path ,class: "btn-default btn-mail" do
          メールアドレスで登録
          %i.far.fa-envelope
        %button#facebook-login.btn-sns.btn-sns-facebook
          %i.fab.fa-facebook
          = link_to "Facebookで登録", user_facebook_omniauth_authorize_path
          / Facebookで登録
        %button#google-login.btn-sns.btn-sns-google
          %i.fab.fa-google-plus-g
          = link_to "Googleで登録", user_google_oauth2_omniauth_authorize_path
          / Googleで登録

/   %form#login_form_facebook{:action => "/jp/signup/facebook/", :method => "POST", :novalidate => "novalidate"}   facebook認証とgoogle認証で使う。
/     %input{:name => "__csrf_value", :type => "hidden", :value => "4e97b39adc302bb741ea51d528041d2bc148a2f01d2e2af05e112cc27344da870d6dc0d34320487de1fee3716c99dc4063f5241392ec211d71e9c2019cf5f36ef"}/
/     %input{:name => "nickname", :type => "hidden", :value => ""}/
/     %input{:name => "email", :type => "hidden", :value => ""}/
/     %input{:name => "facebook_user_id", :type => "hidden", :value => ""}/
/     %input{:name => "facebook_access_token", :type => "hidden", :value => ""}/
/     %input{:name => "login_type", :type => "hidden", :value => "facebook"}/
/     %input{:name => "after_save_callback", :type => "hidden", :value => "https://www.mercari.com/jp/"}/
/   %form#login_form_google{:action => "/jp/signup/google/", :method => "POST", :novalidate => "novalidate"}
/     %input{:name => "__csrf_value", :type => "hidden", :value => "4e97b39adc302bb741ea51d528041d2bc148a2f01d2e2af05e112cc27344da870d6dc0d34320487de1fee3716c99dc4063f5241392ec211d71e9c2019cf5f36ef"}/
/     %input{:name => "nickname", :type => "hidden", :value => ""}/
/     %input{:name => "email", :type => "hidden", :value => ""}/
/     %input{:name => "google_user_id", :type => "hidden", :value => ""}/
/     %input{:name => "google_access_token", :type => "hidden", :value => ""}/
/     %input{:name => "login_type", :type => "hidden", :value => "google"}/
/     %input{:name => "after_save_callback", :type => "hidden", :value => "https://www.mercari.com/jp/"}/
/   %input#google_client_id{:type => "hidden", :value => "238694260676-l0gp5j3hs9p8l2hjmnt126q0b4iin34r.apps.googleusercontent.com"}/
/   %input#facebook_app_id{:type => "hidden", :value => "466308336793848"}/

app/views/users/edit.html.haml
%main.l-container
  = render "sidebar"
  .l-content-main
    %h2.l-chapter-head プロフィール
    .setting-profile-icon
      %figure
        =image_tag "//static-mercari-jp-imgtr2.akamaized.net/images/member_photo_noimage_thumb.png", size: "60*60", class: "mypic"
      %input{ type: "text", value: "#{current_user.nickname}", name: "nickname", placeholder: "例）メルカリ太郎", class: "input-text"}
    .setting-profile-content
      %textarea{ name: "introduction", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", class: "textarea-default"}
      %button{ type: "submit", class: "btn-update-box btn-update-red"} 変更する

app/views/users/identification.html.haml
%main.l-container
  = render "sidebar"
  .l-content
    %section.l-chapter-container.mypage-identification
      %h2.l-chapter-head
        本人情報の登録
      %p.text-center
        お客さまのあんしん・あんぜんな取引のため、本人情報のご登録をお願いしております。
      = form_for current_user, html: {class: "l-single-inner"} do |f|
        .form-group
          = f.label :nickname ,"お名前"
          %span.form-require
            必須
          = f.text_field :nickname, placeholder: "例）山田", class: "input-default"
          = f.text_field :nickname, placeholder: "例）彩", class: "input-default"
        .form-group
          = f.label :nickname, "お名前カナ"
          %span.form-require
            必須
          = f.text_field :nickname, placeholder: "例）ヤマダ", class: "input-default"
          = f.text_field :nickname, placeholder: "例）アヤ", class: "input-default"
        .form-group
          = f.label :nickname, "郵便番号"
          %span.form-arbitrary
            任意
          = f.text_field :nickname, placeholder: "例）1234567", class: "input-default"
        .form-group
          = f.label :nickname, "都道府県"
          %span.form-require
            必須
          .select-wrap-pre
            = f.select :nickname, [["北海道", 0], ["沖縄", 1]], {}, {class: "input-default"}
            %i.fas.fa-angle-down.fa-lg
        .form-group
          = f.label :nickname, "市区町村"
          %span.form-require
            必須
          = f.text_field :nickname, placeholder: "例）横浜市緑区", class: "input-default"
        .form-group
          = f.label :nickname, "番地"
          %span.form-require
            必須
          = f.text_field :nickname, placeholder: "例）青山1−1−1", class: "input-default"
        .form-group
          = f.label :nickname, "建物名"
          %span.form-arbitrary
            任意
          = f.text_field :nickname, placeholder: "例）柳ビル103", class: "input-default"
        .form-group
          = f.label :nickname, "生年月日"
          %span.form-require
            必須
          .birth-form
            .birthday-select-wrap
              .select-wrap
                = f.select :nickname, [["1990", 0], ["2000", 1]], {}, {class: "input-default"}
              %i.fas.fa-angle-down.fa-lg
            %span
              年
            .birthday-select-wrap
              .select-wrap.select-wrap__month
                = f.select :nickname, [["--", 0], ["9", 1]], {}, {class: "input-default"}
              %i.fas.fa-angle-down.fa-lg
            %span
              月
            .birthday-select-wrap
              .select-wrap.select-wrap__day
                = f.select :nickname, [["--", 0], ["30", 1]], {}, {class: "input-default"}
              %i.fas.fa-angle-down.fa-lg
            %span
              日
          %p.form-info-text
            ※出品されたことがある、本人情報未登録のお客さまもご対象となります。
          = f.hidden_field :nickname
          = f.submit "登録する", class: "btn-default btn-red"
          .form-group.text-right
            %p
              =link_to "https://www.mercari.com/jp/help_center/article/423/" do
                本人情報の登録について
                %i.fas.fa-angle-right.fa-lg

app/views/users/logout.html.haml
%main.l-container
  = render "sidebar"
  .logout-box
    %form.logout-box__inner
      .logout-box__inner-btn
        =link_to "ログアウト",destroy_user_session_path, method: :delete, class: "red-logout"

app/views/users/registercard.html.haml
%main.l-container
  = render "sidebar"
  .l-content
    %section.l-chapter-container
      %h2.l-chapter-head クレジットカード情報入力
      %form#add-card-form.l-single-inner{action: "https://www.mercari.com/jp/mypage/card/add/", dataid: "card-form", method: "POST", novalidate: "novalidate"}
        .l-single-content
          .form-group
            %label{for: "payment_card_no"} カード番号
            %span.form-require 必須
            %input#payment_card_no.input-default{datatype: "card", maxlength: "19", placeholder: "半角数字のみ", type: "text", value: ""}/
            %ul#card-no-error-wrapper.has-error-text
            %ul.signup-card-list
              %li
                %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?840690802", width: "49"}/
              %li
                %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?840690802", width:"34"}/
              %li
                %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?840690802", width: "30"}/
              %li
                %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?840690802", width: "32"}/
              %li
                %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?840690802", width: "21"}/
              %li
                %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?840690802", width: "32"}/
              %li
                %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?840690802", width: "32"}/
          .form-group.signup-form-expire
            %label{for: "payment_card_expire"} 有効期限
            %span.form-require 必須
            %br/
            .select-wrap
              %select#payment_card_expire_mm.select-default
                %option{value: "01"} 01
                %option{value: "02"} 02
                %option{value: "03"} 03
                %option{value: "04"} 04
                %option{value: "05"} 05
                %option{value: "06"} 06
                %option{value: "07"} 07
                %option{value: "08"} 08
                %option{value: "09"} 09
                %option{value: "10"} 10
                %option{value: "11"} 11
                %option{value: "12"} 12
              %i.fas.fa-angle-down.fa-2x
              .mozi 月
            %ul#expire-mm-error-wrapper.has-error-text
            .select-wrap
              %select#payment_card_expire_yy.select-default
                %option{value: "18"} 18
                %option{value: "19"} 19
                %option{value: "20"} 20
                %option{value: "21"} 21
                %option{value: "22"} 22
                %option{value: "23"} 23
                %option{value: "24"} 24
                %option{value: "25"} 25
                %option{value: "26"} 26
                %option{value: "27"} 27
                %option{value: "28"} 28
              %i.fas.fa-angle-down.fa-2x
              .mozi 年
            %ul#expire-yy-error-wrapper.has-error-text
          .form-group
            %label{for: "payment_card_security_code"} セキュリティコード
            %span.form-require 必須
            %input#payment_card_security_code.input-default{placeholder: "カード背面4桁もしくは3桁の番号", type: "text", value: ""}/
            %ul#security-code-error-wrapper.has-error-text
            .signup-seqcode
              %label.signup-seqcode-text{for: "label1"}
                %span.form-question> ?
                カード裏面の番号とは？
              %input#label1{type: "checkbox"}/
              .signup-seqcode-info
                %p
                カードの裏面をご参照ください。
                %br/
                %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/signup/seq-card.png?840690802", width: "240"}/
          %button#submit-button.btn-default.btn-red{type: "button"} 追加する

app/views/users/show.html.haml
- breadcrumb :mypage
%main.l-container
  = render "sidebar"
  .l-contents
    %section.mypage-user-icon
      =link_to "https://www.mercari.com/jp/u/840784334/" do
        %figure
          =image_tag "//static-mercari-jp-imgtr2.akamaized.net/images/member_photo_noimage_thumb.png"
        %h2.bold
          = current_user.nickname
        .mypage-number
          %div
            評価
            %span.bold
              0
          %div
            出品数
            %span.bold
              = @count
    %section.mypage-tab-container-notification-todo
      %ul.mypage-tabs
        %li.mypage-tabs-active.active
          %h3
            =link_to "お知らせ","#mypage-tab-notification",data: { toggle: 'tab'}
        %li
          %h3
            =link_to "やることリスト","#mypage-tab-todo",data: { toggle: "tab"}
      .tab-content
        %ul#mypage-tab-notification.mypage-item-list.tab-pane.move-show
          %li
            =link_to "",data: { open: "model" ,model: "banner"},class: "mypage-item-link" do
              %figure
                =image_tag "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", class: "lazyloaded",data: { src: "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png"}
              .mypage-item-body
                .mypage-item-text
                  【あと2日】ファッションアイテムが売れたら“必ず“ポイントがもらえるキャンペーン開催中
                %time
                  %i.far.fa-clock
                  %span
                    6時間前
              %i.far.fa-angle-rig.fa-2x
          %li.mypage-go-list
            =link_to "一覧を見る", "/jp/mypage/notification/"
        %ul#mypage-tab-todo.mypage-item-list.tab-pane
          %li.mypage-item-not-found.bold
            現在、やることリストはありません
    %section.mypage-tab-container
      %h2.mypage-tab-head
        購入した商品
      %ul.mypage-tabs
        %li.mypage-tabs-active.active
          %h3
            =link_to "取引中","#mypage-tab-transaction-now",data: { toggle: 'tab'}
        %li
          %h3
            =link_to "過去の取引","#mypage-tab-transaction-old",data: { toggle: "tab"}

      .tab-content
        %ul#mypage-tab-transaction-now.mypage-item-list.tab-pane.move-show
          = render @orders.where(status: ["stage0","stage1","stage2","stage3"])

          .pagenate
            = paginate(@orders.where(status: ["stage0","stage1","stage2","stage3"]))

          - if @orders.where(status: ["stage0","stage1","stage2","stage3"]).length == 0
            %li.mypage-item-not-found.bold
              取引中の商品がありません

        %ul#mypage-tab-transaction-old.mypage-item-list.tab-pane
          = render @orders.where(status: "stage4")

          .pagenate
            = paginate(@orders.where(status: "stage4"))

          - if @orders.where(status: "stage4").length == 0
            %li.mypage-item-not-found.bold
              過去に取引した商品がありません