config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users do
    get :choice, on: :collection
    post :follow, on: :member
    get :logout, on: :member
    get :edit, on: :member
    get :identification, on: :member
    resources :cards, :only => [:index, :new, :create, :destroy]
    resources :orders, only: :index do
      get :sale, on: :collection
      post :pay, on: :member
    end
  end
  resources :items do
    # get :search, on: :collection
    collection do
      match 'search' => 'items#search', via: [:get, :post], as: :search
    end
    get :option, on: :member
    resources :orders, only: [:new, :create, :show, :update, :destroy]
    resources :comments, only: [:create]
  end

  resources :categories do
    get :select_top, on: :collection
    get :select_mid, on: :collection
  end

  resources :brands do
    get :search, on: :collection
    get :submit, on: :collection
  end

  resources :sizes, only: :index
end

app/views/shared/_footer.html.haml
%footer
  .app-banner
    .app-banner-contents
      .app-banner-inner
        %h2.frima-app スマホでかんたんフリマアプリ
        %p.free-download 今すぐ無料ダウンロード！
        .app-banner-icon
          %img.mercari-icon{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?3633094892"}
          .app-download
            .app-apple
              = link_to items_path, class: 'app-link' do
                %img{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?3633094892"}
            .app-android
              = link_to items_path, class: 'app-link' do
                %img{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?3633094892"}
      %img.smartphone{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?3633094892"}

  .global-footer
    .footer-nav
      %ul.content-list
        %li.footer-cell
          %h2.footer-head メルカリについて
          %ul
            %li
              = link_to "会社概要（運営会社）", items_path, class: "footer-link"
            %li
              = link_to "プライバシーポリシー", items_path, class: "footer-link"
            %li
              = link_to "メルカリ利用規約", items_path, class: "footer-link"
            %li
              =link_to "メルカリ利用規約・有償ポイントに関する特約", items_path, class: "footer-link"
            %li
              =link_to "あんしんスマホサポート制度に関する利用規約", items_path, class: "footer-link"
            %li
              =link_to "コンプライアンスポリシー", items_path, class: "footer-link"
            %li
              =link_to "個人データの安全管理に関わる基本方針", items_path, class: "footer-link"
            %li
              =link_to "特定商取引に関する表記", items_path, class: "footer-link"
            %li
              =link_to "資金決済法に基づく表示", items_path, class: "footer-link"
            %li
              =link_to "法令順守と犯罪防止のために", items_path, class: "footer-link"
            %li
              =link_to "採用情報", items_path, class: "footer-link"
        %li.footer-cell
          %h2.footer-head メルカリを見る
          %ul
            %li
              =link_to "カテゴリー一覧", items_path, class: "footer-link"
            %li
              =link_to "ブランド一覧", items_path, class: "footer-link"
            %li
              =link_to "出品地域一覧", items_path, class: "footer-link"
            %li
              =link_to "公式ブログ", items_path, class: "footer-link"
            %li
              =link_to "公式Twitter", items_path, class: "footer-link"
            %li
              =link_to "公式Facebook", items_path, class: "footer-link"
        %li.footer-cell
          %h2.footer-head ヘルプ＆ガイド
          %ul
            %li
              =link_to "メルカリガイド", items_path, class: "footer-link"
            %li
              =link_to "メルカリロゴ利用ガイドライン", items_path, class: "footer-link"
            %li
              =link_to "お知らせ", items_path, class: "footer-link"
            %li
              =link_to "らくらくメルカリ便とは", items_path, class: "footer-link"
            %li
              =link_to "ゆうゆうメルカリ便とは", items_path, class: "footer-link"
            %li
              =link_to "大型らくらくメルカリ便とは", items_path, class: "footer-link"
            %li
              =link_to "車体取引ガイド", items_path, class: "footer-link"
            %li
              =link_to "返品・返金ポリシー", items_path, class: "footer-link"
            %li
              =link_to "メルカリあんしん・あんぜん宣言！", items_path, class: "footer-link"
            %li
              =link_to "偽ブランド品撲滅への取り組み", items_path, class: "footer-link"
            %li
              =link_to "メルカリボックス", items_path, class: "footer-link"
        %li.footer-cell
          %h2.footer-head 国
          %ul.footer-nav-lang
            %li
              = link_to items_path, class: 'language' do
                %img.country-flag{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/flag_us.png?3633094892"}
                .country United States
            %li
              = link_to items_path, class: 'language' do
                %img.country-flag{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/flag_uk.png?3633094892"}
                .country United Kingdom
            %li
              = link_to items_path, class: 'language' do
                %img.country-flag{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/flag_jp.png?3633094892"}
                .country 日本

    = link_to items_path, class: 'footer-logo' do
      %img.footer-mercari-logo{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?3633094892"}
    %p.footer-copyright ©️ 2018 Mercari

  //出品カメラ
  = link_to items_path, class: 'footer-sell-btn' do
    .sell 出品
    %i.fas.fa-camera

app/views/shared/_footer_content.html.haml
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        =link_to "プライバシーポリシー","https://www.mercari.com/jp/privacy/"
      %li
        =link_to "メルカリ利用規約","https://www.mercari.com/jp/tos/"
      %li
        =link_to "特定商取引に関する表記","https://www.mercari.com/jp/tokutei/"
  =link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3942658967", alt: "mercari", height: "65", width: "80"),"https://www.mercari.com/jp/"
  %p
    %small © 2018 Mercari

app/views/shared/_global-footer.html.haml
%footer
  .app-banner
    .app-banner-contents
      .app-banner-inner
        %h2.frima-app スマホでかんたんフリマアプリ
        %p.free-download 今すぐ無料ダウンロード！
        .app-banner-icon
          %img.mercari-icon{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?3633094892"}
          .app-download
            .app-apple
              = link_to items_path, class: 'app-link' do
                %img{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?3633094892"}
            .app-android
              = link_to items_path, class: 'app-link' do
                %img{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?3633094892"}
      %img.smartphone{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?3633094892"}

  .global-footer
    .footer-nav
      %ul.content-list
        %li.footer-cell
          %h2.footer-head メルカリについて
          %ul
            %li
              = link_to "会社概要（運営会社）", items_path, class: "footer-link"
            %li
              = link_to "プライバシーポリシー", items_path, class: "footer-link"
            %li
              = link_to "メルカリ利用規約", items_path, class: "footer-link"
            %li
              =link_to "メルカリ利用規約・有償ポイントに関する特約", items_path, class: "footer-link"
            %li
              =link_to "あんしんスマホサポート制度に関する利用規約", items_path, class: "footer-link"
            %li
              =link_to "コンプライアンスポリシー", items_path, class: "footer-link"
            %li
              =link_to "個人データの安全管理に関わる基本方針", items_path, class: "footer-link"
            %li
              =link_to "特定商取引に関する表記", items_path, class: "footer-link"
            %li
              =link_to "資金決済法に基づく表示", items_path, class: "footer-link"
            %li
              =link_to "法令順守と犯罪防止のために", items_path, class: "footer-link"
            %li
              =link_to "採用情報", items_path, class: "footer-link"
        %li.footer-cell
          %h2.footer-head メルカリを見る
          %ul
            %li
              =link_to "カテゴリー一覧", items_path, class: "footer-link"
            %li
              =link_to "ブランド一覧", items_path, class: "footer-link"
            %li
              =link_to "出品地域一覧", items_path, class: "footer-link"
            %li
              =link_to "公式ブログ", items_path, class: "footer-link"
            %li
              =link_to "公式Twitter", items_path, class: "footer-link"
            %li
              =link_to "公式Facebook", items_path, class: "footer-link"
        %li.footer-cell
          %h2.footer-head ヘルプ＆ガイド
          %ul
            %li
              =link_to "メルカリガイド", items_path, class: "footer-link"
            %li
              =link_to "メルカリロゴ利用ガイドライン", items_path, class: "footer-link"
            %li
              =link_to "お知らせ", items_path, class: "footer-link"
            %li
              =link_to "らくらくメルカリ便とは", items_path, class: "footer-link"
            %li
              =link_to "ゆうゆうメルカリ便とは", items_path, class: "footer-link"
            %li
              =link_to "大型らくらくメルカリ便とは", items_path, class: "footer-link"
            %li
              =link_to "車体取引ガイド", items_path, class: "footer-link"
            %li
              =link_to "返品・返金ポリシー", items_path, class: "footer-link"
            %li
              =link_to "メルカリあんしん・あんぜん宣言！", items_path, class: "footer-link"
            %li
              =link_to "偽ブランド品撲滅への取り組み", items_path, class: "footer-link"
            %li
              =link_to "メルカリボックス", items_path, class: "footer-link"
        %li.footer-cell
          %h2.footer-head 国
          %ul.footer-nav-lang
            %li
              = link_to items_path, class: 'language' do
                %img.country-flag{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/flag_us.png?3633094892"}
                .country United States
            %li
              = link_to items_path, class: 'language' do
                %img.country-flag{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/flag_uk.png?3633094892"}
                .country United Kingdom
            %li
              = link_to items_path, class: 'language japan' do
                %img.country-flag{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/flag_jp.png?3633094892"}
                .country 日本

    = link_to items_path, class: 'footer-logo' do
      %img.footer-mercari-logo{ src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?3633094892"}
    %p.footer-copyright ©️ 2018 Mercari

  //出品カメラ
  = link_to new_item_path, class: 'footer-sell-btn' do
    .sell 出品
    %i.fas.fa-camera

app/views/shared/_global-header.html.haml
.default-container
  %header
    .header.visible
      .header-inner
        .inner-box
          .logo
            = link_to items_path, class: 'logo-link' do
              %img{class: :"mercari", src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3633094892"}
          = search_form_for $search, url: search_items_path, class: 'header-form' do |f|
            = f.search_field :name_cont, class: 'input-default', placeholder: "キーワードから探す"
            .actions= f.submit "検索"
            %i.fas.fa-search
          %link{:href => "https://fonts.googleapis.com/css?family=Faster+One", :rel => "stylesheet"}/



        .header-nav-box
          .l-left
            .header-nav
              .search-category
                = link_to "カテゴリーから探す",  categories_path, class: 'header-nav-root'

              .search-brand
                = link_to "ブランドから探す", items_path, class: 'header-nav-root'

          - if user_signed_in?
            .l-right
              .header-mypage
                = link_to user_path(current_user), class: 'header-nav' do
                  .header-mypage-link
                    = image_tag "//static-mercari-jp-imgtr2.akamaized.net/images/member_photo_noimage_thumb.png", alt: "sample", class: "my-avatar"
                    %span.header-myp
                      = current_user.nickname
                      さんのマイページ
                .header-mypage-notice
                  %i.far.fa-bell
                  %span.header-notice お知らせ

                .header-mypage-todo
                  %i.fa.fa-check
                  %span.header-todo やることリスト
          - else
            .l-right
              .header-login-nav
                .login-btn
                  = link_to "ログイン", new_user_session_path, class: 'btn-red'
                .register-btn
                  = link_to "新規会員登録", choice_users_path, class: 'header-signup'

app/views/shared/_header_content.html.haml
%header.single-header
  %h1
    =link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3942658967", alt: "mercari"),"https://www.mercari.com/jp/"