config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users do
    get :choice, on: :collection
    post :follow, on: :member
    get :logout, on: :member
    get :edit, on: :member
    get :identification, on: :member
    resources :cards, :only => [:index, :new, :create, :destroy]
    resources :orders, only: :index do
      get :sale, on: :collection
      post :pay, on: :member
    end
  end
  resources :items do
    # get :search, on: :collection
    collection do
      match 'search' => 'items#search', via: [:get, :post], as: :search
    end
    get :option, on: :member
    resources :orders, only: [:new, :create, :show, :update, :destroy]
    resources :comments, only: [:create]
  end

  resources :categories do
    get :select_top, on: :collection
    get :select_mid, on: :collection
  end

  resources :brands do
    get :search, on: :collection
    get :submit, on: :collection
  end

  resources :sizes, only: :index
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :user
  belongs_to :size
  belongs_to :order
  belongs_to :brand
  has_many :images, dependent: :destroy
  has_many :comments

  accepts_nested_attributes_for :images

  enum condition: [:lv0, :lv1, :lv2, :lv3, :lv4, :lv5, :lv6]
  enum shipping_fee: [:f0, :f1, :f2]
  enum shipping_from: [:noarea, :hkd, :aomr, :iwt, :myg, :akt, :ymgt, :hksm, :ibrk, :tcg, :gnm, :sitm, :cb, :tky, :kngw, :nigt, :tym, :iskw, :hki, :ymns, :ngn, :gf, :szok, :aic, :mie, :siga, :kyt, :osk, :hyg, :nara, :wkym, :ttr, :smn, :okym, :hrsm, :ymgc, :tksm, :kgw, :ehm, :kuc, :hkok, :saga, :ngsk, :kmmt, :oit, :myzk, :kgsm, :oknw, :notyet]
  enum shipping_date: [:d0, :d1, :d2, :d3]
  enum shipping_way: [:w0, :w1, :w2, :w3, :w4, :w5, :w6, :w7, :w8, :w9]

  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :size_id, presence: true
  validates :price, presence: true, numericality: { only_integer: true , greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  validates :condition, presence: true, exclusion: { in: %w(lv0) }
  validates :shipping_from, presence: true, exclusion: { in: %w(noarea) }
  validates :shipping_date, presence: true, exclusion: { in: %w(d0) }
  validates :shipping_fee, presence: true, exclusion: { in: %w(f0) }
  validates :shipping_way, presence: true, exclusion: { in: %w(w0) }
  validates :category_id, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    items = Item.includes(:user).order("created_at DESC").page(params[:page]).per(12)
    ids = Order.pluck(:item_id)
    @items = items.where.not(id: ids)
    $search = Item.ransack(params[:q])
  end

  def new
    @large_categories = Category.find_by_sql(['select * from categories where depth is NULL'])
    @item = Item.new
    @item.images.build
    render layout: 'layout_content'
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render :action => "new", :layout => "layout_content"
    end
  end

  def show
    gon.address = current_user.address.present? if user_signed_in?
    @ids = Order.pluck(:item_id)
    @item = Item.find(params[:id])
    @images = Image.where(item_id: @item.id)
    @small_category = @item.category

    if @item.category.depth.include?("/")
      @small_category_depth = @item.category.depth.split("/").last.to_i
      @medium_category = Category.find(@small_category_depth)
      @large_category = Category.find(@medium_category.depth)
    else
      @medium_category = Category.find(@item.category_id) #中カテどまりの商品
      @large_category = Category.find(@medium_category.depth)
    end

    @items = Item.where(user_id: @item.user_id).where.not(id: @item.id).limit(6) # 同じ出品者の商品
    @same_brand_items = Item.where(brand_id:@item.brand_id).where.not(id: @item.id).limit(6) # 同じブランドの商品
    @comments = @item.comments
    @comment = Comment.new

    redirect_to option_item_path if @item.user == current_user
  end

  def option
    @item = Item.find(params[:id])
    @images = Image.where(item_id: @item.id)
    @comments = @item.comments
    @comment = Comment.new
    @small_category = @item.category

    if @item.category.depth.include?("/")
      @small_category_depth = @item.category.depth.split("/").last.to_i
      @medium_category = Category.find(@small_category_depth)
      @large_category = Category.find(@medium_category.depth)
    else
      @medium_category = Category.find(@item.category_id) #中カテどまりの商品
      @large_category = Category.find(@medium_category.depth)
    end
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.user_id == current_user.id
      if @item.destroy
        redirect_to items_path
      else
        redirect_to  option_item(@item)
      end
    end
  end

  def edit
    @item = Item.find(params[:id])
    @default_category = @item.category
    @default_size = @item.size
    @item.brand == nil ? @default_brand = "" : @default_brand = @item.brand.name
    @depth = @default_category.depth.split("/")
    render layout: 'layout_content'
  end

  def update
    @item = Item.find(params[:id])
    if @item.user_id == current_user.id
      if @item.update(item_params)
        redirect_to items_path
      else
        redirect_to edit_item_path(@item)
      end
    end
  end

  def search
    @search = Item.ransack(params[:q])
    @result = @search.result
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :price, :condition, :category_id, :size_id, :brand_id, :shipping_from, :shipping_date, :shipping_fee, :shipping_way, images_attributes: [:image]).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/views/items/_comment.html.haml
.message-content__comments
  .comments-box
    .message-user
      = image_tag "img.jpeg", alt: "sample", class: "avatar"
    .message-user-name
      石川啄木
    .message-body
      .text
        うさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいいうさぎかわいい
      .icons
        .icons-left
          %i.far.fa-clock
          %span 456日前
        .icons-right
          = link_to items_path, class: "message-report" do
            %i.fas.fa-flag-checkered
      %i.fas.fa-caret-left

app/views/items/_item.html.haml
%section.items-box.show-items
  = link_to item_path(item.id), class: 'item-link' do
    %figure.items-box-photo
      = image_tag (item.images.first.image.url), class: "item-image"
    .products
      %h3.products__name.show-items-name
        = item.name
      .products__price.show-items-price
        .products__price--fig
          ¥
          = item.price
        .products__price--likes
          %i.icon-like-border
            %i.far.fa-heart
          %span.num 44
        %p.products__price--tax.show-items-tax (税込)

app/views/items/_size.html.haml
.new-itembox__right--group.size-box
  %span
    サイズ
    .require
      必須
  //男女服のサイズ
  = f.select :size, Item.sizes_i18n.slice(:s0, :s1, :s2, :s3, :s4, :s5, :s6, :s7, :s8, :s9, :s10).invert, {}, class: 'select-new s-wear', placeholder: 0
  //女性靴のサイズ
  = f.select :size, Item.sizes_i18n.slice(:s0, :s11, :s12, :s13, :s14, :s15, :s16, :s17, :s18, :s19, :s20, :s21, :s22, :s23, :s24, :s25, :s26).invert, {}, class: 'select-new s-f-shoes', placeholder: 0
  //男性靴のサイズ
  = f.select :size, Item.sizes_i18n.slice(:s0, :s19, :s20, :s21, :s22, :s23, :s24, :s25, :s26, :s27, :s28, :s29, :s30, :s31, :s32, :s33).invert, {}, class: 'select-new s-m-shoes', placeholder: 0
  //タイヤのインチ
  = f.select :size, Item.sizes_i18n.slice(:s0, :s34, :s35, :s36, :s37, :s38, :s39, :s40, :s41, :s42, :s43, :s44, :s45, :s46).invert, {}, class: 'select-new s-tire', placeholder: 0
  //キッズ95センチ未満
  = f.select :size, Item.sizes_i18n.slice(:s0, :s47, :s48, :s49, :s50, :s51).invert, {}, class: 'select-new s-kids95', placeholder: 0
  //キッズ100センチ以上
  = f.select :size, Item.sizes_i18n.slice(:s0, :s52, :s53, :s54, :s55, :s56, :s57, :s58).invert, {}, class: 'select-new s-kids100', placeholder: 0
  //ベビー靴
  = f.select :size, Item.sizes_i18n.slice(:s0, :s59, :s60, :s61, :s62, :s63, :s64, :s65, :s66).invert, {}, class: 'select-new s-baby', placeholder: 0
  //スキー板
  = f.select :size, Item.sizes_i18n.slice(:s0, :s67, :s68, :s69, :s70, :s71, :s72, :s73).invert, {}, class: 'select-new s-ski', placeholder: 0
  //ボード
  = f.select :size, Item.sizes_i18n.slice(:s0, :s74, :s75, :s76, :s77, :s78, :s79, :s80).invert, {}, class: 'select-new s-board', placeholder: 0

app/views/items/index.html.haml
.top-main-visual
  .slider
    .box1
      .top-main-visual
        .top-main-visual__content
          %h2
            スマホでかんたん
            %br
            フリマアプリ
          %p
            メルカリはスマホカメラからすぐに出品できる
            購入時も安心な独自システムのアプリです
          %img{class: :appicon, alt: :"画像", border: :"0", src: :"//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?3371656568"}/
          %img{class: :appicon, alt: :"画像", border: :"0", src: :"//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?3371656568"}/
        .top-main-visual__image
          %img{height: :"390px", width: :"440px", alt: :"画像", border: :"0", src: :"//www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?3371656568"}/
    .box2
    .box3
    .box4

.contents
  %section.top-image

  %section.pickup-container
    %h2.pickup-head ピックアップ全商品

    %section.items-box-container
      %h3.text-center
        = link_to "新着アイテム", items_path, class: 'genre'
      .items-box-content

        = render @items

      .items-pagenate
        = paginate(@items)

      .view-all
        = link_to "すべての商品を見る", items_path, class: 'all-link'

app/views/items/new.html.haml
= form_for @item do |f|
  .new-header
    %h2 商品の情報を入力

  .new-input-error
    - if @item.errors.any?
      #error_explanation.alert.alert-danger
        %ul
          - @item.errors.full_messages.each do |message|
            %li
              = message

  .new-upload
    %span
      出品画像
      .require 必須
    %p 最大4枚までアップロードできます
    .new-upload__image-sec
      %ul#output
      .new-upload__image
        #dragarea.new-upload__image-dd
          %pre
            ドラッグアンドドロップ
            またはクリックしてファイルをアップロード
        = f.fields_for :images do |fin|
          = fin.file_field :image, class: 'hidden', id: 'fileinput', required: true

    .new-upload__image
      .new-upload__image-dd
        %pre
          ドラッグアンドドロップ
          またはクリックしてファイルをアップロード
      = f.fields_for :images do |fin|
        = fin.file_field :image, class: 'hidden', required: true

  .new-itembox
    %span
      商品名
      .require 必須
    = f.text_field :name, class: 'input-new',placeholder: "商品名（必須 40文字まで)"
    %span
      商品の説明
      .require 必須
    = f.text_area :description, class: 'textareanew-new', placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。', rows: :"5"

  .new-itembox
    .new-itembox__left
      %h3 商品の詳細
    .new-itembox__right
      .new-itembox__right--group.cate
        %span
          カテゴリー
          .require
            必須

        = f.collection_select :category, Category.find_by_sql(['select * from categories where depth is NULL']), :id, :name, class: 'select-new', prompt: "---"

      .new-itembox__right--group.size-hidden

      .new-itembox__right--group.brand-box

      .new-itembox__right--group
        %span
          商品の状態
          .require 必須
        = f.select :condition, Item.conditions_i18n.invert, {}, class: 'select-new', placeholder: 0

  .new-itembox
    .new-itembox__left
      %h3
        配送について
        = fa_icon 'question-circle'
    .new-itembox__right
      .new-itembox__right--group
        %span
          配送料の負担
          .require 必須
        = f.select :shipping_fee, Item.shipping_fees_i18n.invert, {}, class: 'select-new fee', placeholder: 0
      .new-itembox__right--group#sw-in
        %span
          配送の方法
          .require 必須
        = f.select :shipping_way, Item.shipping_ways_i18n.invert, {}, class: 'select-new', placeholder: 0
      .new-itembox__right--group#sw-out
        %span
          配送の方法
          .require 必須
        = f.select :shipping_way, Item.shipping_ways_i18n.slice(:w0, :w1, :w6, :w7, :w3).invert, {}, class: 'select-new', placeholder: 0
      .new-itembox__right--group
        %span
          発送元の地域
          .require 必須
        = f.select :shipping_from, Item.shipping_froms_i18n.invert, {}, class: 'select-new', placeholder: 0
      .new-itembox__right--group
        %span
          発送までの日数
          .require 必須
        = f.select :shipping_date, Item.shipping_dates_i18n.invert, {}, class: 'select-new', placeholder: 0

  .new-itembox
    .new-itembox__left
      %h3
        販売価格(300〜9,999,999)
        = fa_icon 'question-circle'
    .new-itembox__right
      %ul.price-container
        %li.price-container__field
          .price-container__field--left
            %span
              価格
              .require 必須
          .price-container__field--right
            ￥
            = f.text_field :price, class: 'price-container__field--right-input',placeholder: "例）300"
        %li.price-container__field.middle
          .price-container__field--left
            %p 販売手数料
          .price-container__field--right
            %p.commission -
        %li.price-container__field
          .price-container__field--left
            %p 販売利益
          .price-container__field--right
            %p.profits -

  .new-itembox
    %p
      = link_to "禁止されている出品", items_path, class: "heed"
      、
      = link_to "行為", items_path, class: "heed"
      を必ずご確認ください。
    %p
      またブランド品でシリアルナンバー等がある場合はご記載ください。
      = link_to "偽ブランドの販売", items_path, class: "heed"
      は犯罪であり処罰される可能性があります。
    %p
      また、出品をもちまして
      = link_to "加盟店規約", items_path, class: "heed"
      に同意したことになります。
    = f.submit '出品する', class: 'new-itembox__create-btn'
    = link_to :back, class: "new-submit"do
      .new-itembox__back-btn もどる

app/views/items/option.html.haml
- breadcrumb :item_name, @item

//商品情報
%section.item-show-container
  %h1.item-name
    = @item.name
  .item-main-content
    .item-photo
      .owl-carousel
        .owl-stage-outer
          .owl-stage
            .owl-item.active
              .owl-inner
                - @images.each do |image|
                  =image_tag (image.image.url)
        .owl-dots
          = render partial: "image", collection: @images

    %table.item-detail-table
      %tbody
        %tr
          %th 出品者
          %td
            = link_to"#{@item.user.nickname}", items_path, class: "seller-name"
        %tr
          %th カテゴリー
          %td
            = link_to items_path, class: "top" do
              = @large_category.name

            = link_to items_path, class: "middle" do
              %i.fas.fa-angle-right
              = @medium_category.name

            -if @small_category_depth.present?
              = link_to items_path, class: "bottom" do
                %i.fas.fa-angle-right
                = @small_category.name

        %tr
          %th ブランド
          %td
            = link_to "#{@item.brand.name}", items_path, class: "brand" if @item.brand.present?
        %tr
          %th 商品のサイズ
          %td
            = @item.size.name if @item.size.present?
        %tr
          %th 商品の状態
          %td
            = @item.condition_i18n
        %tr
          %th 配送料の負担
          %td
            = @item.shipping_fee_i18n
        %tr
          %th 配送の方法
          %td
            = @item.shipping_way_i18n
        %tr
          %th 配送元地域
          %td
            = link_to "#{@item.shipping_from_i18n}", items_path, class: "prefecture"
        %tr
          %th 発送日の目安
          %td
            = @item.shipping_date_i18n

  .item-price-box
    %span.price
      = "¥" + number_with_delimiter("#{@item.price}")
    %span.tax （税込）
    %span.shipping-fee
      = @item.shipping_fee_i18n

  .item-description
    %p.item-description-inner
      = @item.description

//出品オプション
.listing-item-change-box
  = link_to "商品の編集", "/items/#{@item.id}/edit", class: "btn-red btn-default"
  %p.text-center or
  .btn-gray.btn-default 出品を一旦停止する
  = link_to "この商品を削除する", "", id: "modal-open",class: "btn-gray btn-default"

//コメントゾーン
.item-detail-message.option-last
  .message-container
    //コメント一覧
    .message-content
      = render @comments
    //コメント投稿部分
    .message-content
      %p
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      = form_with url: "/items/#{@item.id}/comments" do |f|
        = f.text_area :text, class: 'comment-form'
        = f.submit "コメントする", class: 'comment-btn'


//modalウィンドウ
%aside.modal.is-show.is-animate
  .modal-inner.modal-banner
    .modal-body
      .modal-head.bold 確認
      削除すると二度と復活できません。
      %br 削除する代わりに停止することもできます。
      %br
      %br 本当に削除しますか？
    .modal-box
      .modal-btn.modal-btn-cancel キャンセル
      = link_to "削除する", "/items/#{@item.id}", id: "modal-open",class: "modal-btn modal-btn-submit", method: :delete

app/views/items/search.html.haml
- breadcrumb :searchkeyword, params[:q]
.contents
  .search-sidebar
    .search-sidebar__sort
      %p 並び替え
      = sort_link(@search, :price, order: :desc, hide_indicator: true) do
        .price-order-desc 価格の高い順
      = sort_link(@search, :price, order: :asc, hide_indicator: true) do
        .price-order-asc 価格の安い順
      = sort_link(@search, :created_at, order: :desc, hide_indicator: true) do
        .createdat-order-desc 出品の古い順
      = sort_link(@search, :created_at, order: :asc, hide_indicator: true) do
        .createdat-order-desc 出品の新しい順
    .search-sidebar__panel
      %p 詳細検索
      = search_form_for @search, url:search_items_path, html: { method: :post } do |f|
        %p
        %i.fas.fa-plus
        = f.label :name_cont, 'キーワード追加'
        %br
        = f.search_field :name_cont
        %p
        %i.fas.fa-list-ul
        = f.label :category_id_eq, 'カテゴリ選択'
        %br
        = f.collection_select :category_id, @depth1, :id, :name
        %p
        %i.fas.fa-tags
        = f.label :brand_name_cont, 'ブランド'
        %br
        = f.search_field :brand_name_cont
        %p
        %i.fas.fa-expand
        = f.label :size_id_eq, 'サイズ選択'
        %br
        = f.collection_select :size_id, @size, :id, :name
        %p
        %i.fas.fa-money-bill-wave
        = f.label :price_gteq, "価格"
        %br
        = f.text_field :price_gteq
        = f.label :price_lteq, "~"
        = f.text_field :price_lteq
        %p
        %i.fas.fa-star
        = f.label :condition_id_in, '状態'
        %br
        = f.collection_check_boxes :condition_in, Item.conditions, :last, :first do |b|
          = b.check_box
          = Item.conditions_i18n[b.object.send(:first)]
        %p
        %i.fas.fa-truck
        = f.label :shipping_fee_id_in, '配送料負担'
        %br
        = f.collection_check_boxes :shipping_fee_in, Item.shipping_fees, :last, :first do |b|
          = b.check_box
          = Item.shipping_fees_i18n[b.object.send(:first)]
        %p
        %i.fas.fa-shopping-cart
        = f.label :order_status_in, '販売状況'
        %br
        = f.collection_check_boxes :order_status, Order.statuses, :last, :first do |b|
          = b.check_box
          = Order.statuses_i18n[b.object.send(:first)]
        %br
        = f.submit 'クリア', type: :reset
        = f.submit
  %section.search-result-container
    .search-result-head
      - if @result.length == 0
        = "検索結果 #{@result.length}件"
      - else
        = "検索結果 1-#{@result.length}件"

    %section.items-box-container
      .items-box-content

        = render @result

app/views/items/show.html.haml
- breadcrumb :item_name, @item

//商品情報
%section.item-show-container
  %h1.item-name
    = "#{@item.name}"
  %p.item-wording
    #{@item.name}は、1234回の取引実績を持つ
    = link_to "#{@item.user.nickname}", items_path, class: "seller"
    さんから出品されました。
    #{@item.shipping_from_i18n}から#{@item.shipping_date_i18n}で発送されます。
  .item-main-content
    .item-photo
      .owl-carousel
        .owl-stage-outer
          .owl-stage
            .owl-item.active
              .owl-inner
                - @images.each do |image|
                  =image_tag (image.image.url)
        .owl-dots
          = render partial: "image", collection: @images
    %table.item-detail-table
      %tbody
        %tr
          %th 出品者
          %td
            = link_to"#{@item.user.nickname}", items_path, class: "seller-name"
            .face
              .item-user-ratings
                %i.fas.fa-laugh
                55
              .item-user-ratings
                %i.fas.fa-meh
                3
              .item-user-ratings
                %i.fas.fa-tired
                0
        %tr
          %th カテゴリー
          %td
            = link_to items_path, class: "top" do
              = @large_category.name

            = link_to items_path, class: "middle" do
              %i.fas.fa-angle-right
              = @medium_category.name

            -if @small_category_depth.present?
              = link_to items_path, class: "bottom" do
                %i.fas.fa-angle-right
                = @small_category.name

        %tr
          %th ブランド
          %td
            = link_to "#{@item.brand.name}", items_path, class: "brand" if @item.brand.present?
        %tr
          %th 商品のサイズ
          %td="#{@item.size.name}" if @item.size.present?
        %tr
          %th 商品の状態
          %td="#{@item.condition_i18n}"
        %tr
          %th 配送料の負担
          %td="#{@item.shipping_fee_i18n}"
        %tr
          %th 配送の方法
          %td="#{@item.shipping_way_i18n}"
        %tr
          %th 配送元地域
          %td
            = link_to "#{@item.shipping_from_i18n}", items_path, class: "prefecture"
        %tr
          %th 発送日の目安
          %td="#{@item.shipping_date_i18n}"

  .item-price-box
    %span.price="¥" + number_with_delimiter("#{@item.price}")
    %span.tax （税込）
    %span.shipping-fee="#{@item.shipping_fee_i18n}"

    = Gon::Base.render_data

  - case @item.id
  - when *@ids
    .item-buy-btn.no-click#not-click
      売り切れました
  -else
    - if user_signed_in?
      .item-buy-btn
        = link_to new_item_order_path(params[:id]), class: "buy-red" do
          購入画面に進む

  .item-description
    %p.item-description-inner
      ="#{@item.description}"
  .item-button-container
    .item-button-left
      = link_to items_path, class: "icon-like" do
        %i.far.fa-heart
        %span いいね
        %span 234
      = link_to items_path, class: "item-report" do
        %i.fas.fa-flag-checkered
        %span 不適切な商品の報告
    .item-button-right
      = link_to items_path, class: "safe" do
        %i.fas.fa-lock
        %span あんしん・安全への取り組み

//コメントゾーン
.item-detail-message
  .message-container
    //コメント一覧
    .message-content
      = render @comments
    //コメント投稿部分
    .message-content
      %p
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      = form_with url: "/items/#{@item.id}/comments" do |f|
        = f.text_area :text, class: 'comment-form'
        - case @item.id
        - when *@ids
          .not-comment#not-click
            売り切れのためコメントできません
        -else
          - if user_signed_in?
            = f.submit "コメントする", class: 'comment-btn'
          - else
            .comment-btn.not-push ログインしてください


//ネクストリンク
.nav-item-link-prev-next
  .nav-item-link-prev
    = link_to items_path, class: "prev-item" do
      %i.fas.fa-angle-left
      %span 前の商品
  .nav-item-link-next
    = link_to items_path, class: "next-item" do
      %i.fas.fa-angle-right
      %span 次の商品

//SNS
.item-social-media-box
  %ul.social-media-box
    %li
      = link_to items_path, class: "item-show-fb" do
        %i.fab.fa-facebook
    %li
      = link_to items_path, class: "item-show-tw" do
        %i.fab.fa-twitter
    %li
      = link_to items_path, class: "item-show-pin" do
        %i.fab.fa-pinterest

//他商品
.items-box-container.show
  .items-box-container__in-user-profile
  -if @items.present?
    %h2.item-box-head
      = link_to "#{@item.user.nickname}さんのその他の出品", items_path, class: "another-user-items"
      .item-box-head__content
        = render @items
  .items-box-container__in-brands-item
  -if @item.brand.present?
    %h2.item-box-head
      = link_to "#{@item.brand.name}のその他の商品", items_path, class: "another-brand-items"
      .item-box-head__content
        = render partial: "item", collection: @same_brand_items