config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users do
    get :choice, on: :collection
    post :follow, on: :member
    get :logout, on: :member
    get :edit, on: :member
    get :identification, on: :member
    resources :cards, :only => [:index, :new, :create, :destroy]
    resources :orders, only: :index do
      get :sale, on: :collection
      post :pay, on: :member
    end
  end
  resources :items do
    # get :search, on: :collection
    collection do
      match 'search' => 'items#search', via: [:get, :post], as: :search
    end
    get :option, on: :member
    resources :orders, only: [:new, :create, :show, :update, :destroy]
    resources :comments, only: [:create]
  end

  resources :categories do
    get :select_top, on: :collection
    get :select_mid, on: :collection
  end

  resources :brands do
    get :search, on: :collection
    get :submit, on: :collection
  end

  resources :sizes, only: :index
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    @card = CreditCard.find_by(user_id: current_user.id)
  end

  def new
    @card = CreditCard.new
  end

  def create
    @card = CreditCard.new(card_params)
    if @card.save
      redirect_to user_cards_path(current_user.id)
    else
      render action: :new
    end
  end

  def destroy
    current_user.credit_card.destroy
    redirect_to user_cards_path(current_user.id)
  end

  private
  def card_params
    params.require(:credit_card).permit(:number, :expiration_month, :expriration_year, :security_code).merge(user_id: params[:user_id])
  end
end

app/views/cards/index.html.haml
%main.l-container
  = render "users/sidebar"
  .l-content
    %section.l-chapter-container
      %h2.l-chapter-head 支払い方法
    .l-single-inner
      .l-single-content
        .form-group
          %label クレジットカード一覧
          - if @card.present?
            .card_section
              .card_number
              = @card[0].number
              .expiration_date 有効期限
              = @card[0].expiration_month.to_s + "/" + @card[0].expriration_year.to_s
              %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?840690802", width: "49"}/
          - else
            = link_to new_user_card_path, id: 'add-card-btn' do
              %i.fas.fa-credit-card
              %span.add-card クレジットカードを追加する
    .settings-not-registration
      = link_to '支払い方法について', user_cards_path, id: 'for-way-of-payment'
      %i.fas.fa-angle-right

app/views/cards/new.html.haml
%main.l-container
  = render "users/sidebar"
  .l-content
    %section.l-chapter-container
      %h2.l-chapter-head クレジットカード情報入力
      = form_for @card, url: {controller: :cards, action: :create} do |f|

        .l-single-content
          .form-group
            %label{for: "payment_card_no"} カード番号
            %span.form-require 必須
            = f.text_field :number, id: 'payment_card_no', class: 'input-default',placeholder: "半角数字のみ", maxlength: "19"

            %ul#card-no-error-wrapper.has-error-text
            %ul.signup-card-list
              %li
                %img{alt: "visa", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?840690802", width: "49"}/
              %li
                %img{alt: "master", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?840690802", width:"34"}/
              %li
                %img{alt: "saison", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?840690802", width: "30"}/
              %li
                %img{alt: "jcb", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?840690802", width: "32"}/
              %li
                %img{alt: "amex", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?840690802", width: "21"}/
              %li
                %img{alt: "diners", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?840690802", width: "32"}/
              %li
                %img{alt: "discover", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?840690802", width: "32"}/
          .form-group.signup-form-expire
            %label{for: "payment_card_expire"} 有効期限
            %span.form-require 必須
            %br/
            .select-wrap
              = f.select :expiration_month, (01..12).to_a

              %i.fas.fa-chevron-down.fa-2x
              .mozi 月
            %ul#expire-mm-error-wrapper.has-error-text
            .select-wrap
              = f.select :expriration_year, (19..29).to_a

              %i.fas.fa-chevron-down.fa-2x
              .mozi 年
            %ul#expire-yy-error-wrapper.has-error-text
          .form-group
            %label{for: "payment_card_security_code"} セキュリティコード
            %span.form-require 必須
            = f.text_field :security_code, id: 'payment_card_security_code', class: 'input-default',placeholder: "カード背面4桁もしくは3桁の番号"

            %ul#security-code-error-wrapper.has-error-text
            .signup-seqcode
              %label.signup-seqcode-text{for: "label1"}
                %span.form-question> ?
                カード裏面の番号とは？
              %input#label1{type: "checkbox"}/
              .signup-seqcode-info
                %p
                カードの裏面をご参照ください。
                %br/
                %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/signup/seq-card.png?840690802", width: "240"}/
          = f.submit '追加する', class: 'btn-red-card'